// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AutoCompleteField: typeof import('./src/components/forms/AutoCompleteField.vue')['default']
    CustomerComponent: typeof import('./src/components/offers/CustomerComponent.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    DividerComponent: typeof import('./src/components/DividerComponent.vue')['default']
    Field: typeof import('./src/components/forms/Field.vue')['default']
    FormButton: typeof import('./src/components/forms/FormButton.vue')['default']
    FormField: typeof import('./src/components/forms/FormField.vue')['default']
    FormFIeld: typeof import('./src/components/forms/FormFIeld.vue')['default']
    FormPanel: typeof import('./src/components/forms/FormPanel.vue')['default']
    FormPanelButtons: typeof import('./src/components/forms/FormPanelButtons.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MenuBar: typeof import('./src/components/MenuBar.vue')['default']
    OfferDetails: typeof import('./src/components/offers/OfferDetails.vue')['default']
    OfferLineComponent: typeof import('./src/components/offers/lines/OfferLineComponent.vue')['default']
    OfferLinesPanel: typeof import('./src/components/offers/lines/OfferLinesPanel.vue')['default']
    OfferStatistics: typeof import('./src/components/offers/OfferStatistics.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PaginationBar: typeof import('./src/components/PaginationBar.vue')['default']
    PopupModal: typeof import('./src/components/PopupModal.vue')['default']
    ProductCombobox: typeof import('./src/components/offers/lines/ProductCombobox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectField: typeof import('./src/components/forms/SelectField.vue')['default']
    SenderComponent: typeof import('./src/components/offers/SenderComponent.vue')['default']
    TextField: typeof import('./src/components/forms/TextField.vue')['default']
  }
}
